theme: minima
title: SG's GitHub Blog
author: Sander Grondman
email: s.e.grondman@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is merely for practice purposes, giving the opportunity to learn how GitHub works

# social links
twitter_username: realdonaldtrump # DO NOT include the @ character, or else the build will fail!
github_username:  Sandergrondman # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
